# Generated by Django 5.0.3 on 2024-03-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weeknesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indefinido')], default='M', max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.IntegerField()),
                ('first_apparition', models.CharField(max_length=50)),
                ('history', models.TextField()),
                ('image', models.ImageField(upload_to='catalogue/static/imgs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.skills')),
                ('weeknesses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.weeknesses')),
            ],
        ),
    ]
